import {CUPS,RIVALS,RACE_LENGTH,MAX_SCORE,cupUnlocked,weeklyScores,medal,racePlace} from './arena.js';
const portrait=(tone='',className='')=>`<img class="racer-portrait ${tone} ${className}" src="./assets/iskra.png" alt="" width="1254" height="1254">`;
const participants=score=>[{name:'Ты и Искра',score,tone:'you'},...RIVALS];
export function arenaLobby(progress,challenge){
  const a=progress.arena,weekly=weeklyScores(a),wins=a?.wins||0,medals=CUPS.filter(c=>(a?.best[c.id]||0)>=60).length;
  return `<section class="arena-lobby"><div class="arena-hero"><div class="arena-hero-copy"><span class="mission-kicker">ГОНКИ ДРАКОНОВ</span><h1>Кто зажжёт<br>больше искр?</h1><p>10 задач. Три соперника. Твой ход.</p><div class="arena-pills"><span>✦ Серия = бонус</span><span>↻ Ошибка? Ещё попытка</span></div><button class="primary" data-race="${CUPS.filter(c=>cupUnlocked(c,progress.completed)).at(-1).id}">На старт! →</button></div><div class="arena-hero-art" aria-hidden="true"><span class="orbit orbit-one">✦</span><span class="orbit orbit-two">✧</span><div class="trophy-halo">🏆</div>${portrait('you','hero-racer')}</div></div>
  ${challenge?`<div class="friend-challenge"><span>⚑</span><div><strong>Тебе бросили вызов: ${challenge.score} искр</strong><p>${CUPS.find(c=>c.id===challenge.cupId).name} · те же 10 задач</p></div><button class="primary" data-action="accept-challenge" ${!cupUnlocked(CUPS.find(c=>c.id===challenge.cupId),progress.completed)?'disabled':''}>${cupUnlocked(CUPS.find(c=>c.id===challenge.cupId),progress.completed)?'Принимаю!':'Сначала открой кубок'}</button></div>`:''}
  <div class="arena-section-title"><h2>Выбирай свой кубок</h2><span>${medals} / 5 медалей</span></div><div class="cup-grid">${CUPS.map(c=>{const open=cupUnlocked(c,progress.completed),best=a?.best[c.id]||0;return `<button class="cup-card ${open?'':'cup-locked'}" data-race="${c.id}" ${!open?'disabled':''}><span class="cup-symbol">${open?(best>=60?medal(best):c.symbol):'♧'}</span><strong>${c.name}</strong><small>${c.topic}</small><span class="cup-record">${open?(best?`Рекорд: ${best} ✦`:'Первый старт →'):`После урока ${c.after}`}</span></button>`;}).join('')}</div>
  <div class="arena-bottom-grid"><section class="rival-card"><div class="arena-section-title"><h2>Тебя уже ждут</h2></div><div class="rival-roster">${RIVALS.map(r=>`<div>${portrait(r.tone)}<strong>${r.name}</strong><span>${r.score} ✦</span></div>`).join('')}</div><p class="arena-note">Игровые соперники. Набери 115 искр, чтобы обойти всех.</p><details class="arena-rules"><summary>Как обгонять?</summary><p>Верный ответ с первой попытки: 10 искр. Каждые 3 ответа подряд увеличивают бонус на 2, до +6. После ошибки — 4 искры за решённую задачу. Скорость не влияет на счёт.</p><p>🥉 60 · 🥈 90 · 🥇 115 · Максимум ${MAX_SCORE}.</p></details></section><section class="weekly-card"><span class="mission-kicker">ЛИЧНЫЙ ЗАЧЁТ НЕДЕЛИ</span><h2>Собери пять медалей</h2><div class="weekly-medals">${CUPS.map(c=>`<div title="${c.name}"><span>${medal(weekly[c.id]||0)}</span><small>${weekly[c.id]||'—'}</small></div>`).join('')}</div><p class="arena-note">Новая неделя — новый зачёт. Лучшие рекорды остаются.</p><div class="arena-career"><span><b>${a?.runs||0}</b> гонок</span><span><b>${wins}</b> побед</span></div></section></div></section>`;
}
export function raceHeader(race,icon){
  const completed=race.index+(race.gained?1:0),cup=CUPS.find(c=>c.id===race.cupId);
  return `<div class="race-header"><div class="race-top"><button class="icon-button" data-action="exit-lesson" aria-label="Выйти из гонки">${icon('close')}</button><span>${cup.name}<small>Задача ${Math.min(RACE_LENGTH,race.index+1)} / ${RACE_LENGTH}</small></span><strong aria-live="polite">${race.score} ✦<small>${race.gained?`+${race.gained}!`:race.chain>=2?`Серия ×${race.chain}`:race.index?'Твой ход':'На старт!'}</small></strong></div><div class="race-lanes" aria-label="Гонка: ${racePlace(race.score,completed)} место">${participants(race.score).map(r=>{const score=r.tone==='you'?r.score:Math.round(r.score*completed/RACE_LENGTH);return `<div class="race-lane ${r.tone}"><span class="lane-name">${r.tone==='you'?'Искра':r.name}</span><div class="lane-road ${race.gained?'racer-moving':''}" style="--from:${(r.tone==='you'?Math.max(0,score-race.gained):Math.round(r.score*Math.max(0,completed-1)/RACE_LENGTH))/MAX_SCORE*100}%"><i style="width:${score/MAX_SCORE*100}%"></i><span class="lane-dragon" style="left:${score/MAX_SCORE*100}%">${portrait(r.tone)}</span><span class="lane-finish">⚑</span></div><b>${score}</b></div>`;}).join('')}</div>${race.challenge?`<span class="race-friend-target">⚑ Цель друга: ${race.challenge.score} ✦</span>`:''}</div>`;
}
export function raceResult(race,result){
  const sorted=participants(race.score).sort((a,b)=>b.score-a.score),place=racePlace(race.score),cup=CUPS.find(c=>c.id===race.cupId);
  return `<section class="race-result"><span class="mission-kicker">${cup.name}</span><div class="finish-medal">${medal(race.score)}</div><h1>${place===1?'Кубок твой!':place===2?'Ещё чуть-чуть до победы!':'Искры пойманы!'}</h1><p class="finish-caption">${place} место · ${race.score} искр${result.record?' · Новый рекорд!':''}</p><div class="finish-podium">${sorted.map((r,i)=>`<div class="podium-racer ${r.tone} ${i===0?'winner':''}">${portrait(r.tone)}<div><span>${i+1}</span><strong>${r.name}</strong><b>${r.score} ✦</b></div></div>`).join('')}</div><div class="finish-stats"><span>✦ +${result.xp} XP</span><span>Лучшая серия: ${race.bestChain}</span></div>${race.challenge?`<p class="friend-outcome">${race.score>race.challenge.score?'Вызов принят — ты впереди!':race.score===race.challenge.score?'Ничья! Вы зажгли поровну искр.':`До результата друга: ${race.challenge.score-race.score} искр.`}</p>`:''}<button class="primary wide" data-race="${race.cupId}">${race.score>=MAX_SCORE?'Ещё гонка с новыми задачами':'Реванш!'} ↻</button><button class="secondary wide" data-action="share-race">⚑ Вызвать друга на эту трассу</button><button class="quiet-link wide" data-nav="practice">К другим кубкам</button><p class="arena-note">Мох, Иней и Уголёк — игровые соперники.<br>С другом можно сравнить результат по ссылке.</p></section>`;
}
