import {parse,evaluate} from './logic.js';
import {introFor,introComplete,introCopy,introInstruction,briefFeedback,spellTiles,tableRow,discoveryFor,questionContext} from './play-content.js';
import {mathMarkup,formulaPanel,operatorGuide,renderCalculation} from './math-view.js';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sparks=(count=9)=>`<div class="ambient-sparks" aria-hidden="true">${Array.from({length:count},(_,i)=>`<i style="--i:${i};--x:${9+i*11}%"></i>`).join('')}</div>`;

export function stage({active=false,speech='',sleeping=false,small=false,reaction=''}={}){
  if(small)return `<div class="companion-strip ${reaction}"><button data-play="pet" aria-label="Погладить Искру"><img src="./assets/iskra.png" width="1254" height="1254" alt="" draggable="false"></button><span role="status" class="dragon-bubble">${e(speech)}</span></div>`;
  return `<div class="play-stage ${active?'powered':''} ${sleeping?'sleeping':''} ${reaction}"><div class="stage-landscape"></div>${sparks(5)}<div class="portal-power" aria-hidden="true"></div><button class="stage-dragon" data-play="${sleeping?'wake':'pet'}" aria-label="${sleeping?'Разбудить Искру':'Погладить Искру'}"><img src="./assets/iskra.png" width="1254" height="1254" alt="Искра на волшебной полянке" draggable="false">${sleeping?'<span class="sleep-letters" aria-hidden="true">z Z z</span>':''}</button><div class="scene-message"><span>${active?'ПОЛУЧИЛОСЬ!':'УЧИМСЯ ВМЕСТЕ'}</span><p>${e(speech)}</p></div></div>`;
}

export function renderIntro(lesson,state,header){
  const cfg=introFor(lesson),copy=introCopy(lesson),complete=state.solved||introComplete(lesson,state),isScan=cfg.kind==='scan',wrong=cfg.kind==='spell'&&state.picked!==null&&state.picked!==cfg.answer;
  const speech=complete?'Ты разобрался. Попробуем задачки?':cfg.kind==='wake'?'Я пока сплю… Разбудишь?':'Покажу, как это работает.';
  const pairs=Object.entries(state.env);
  const controls=cfg.kind==='spell'?`<div class="spell-picks">${cfg.choices.map((choice,i)=>`<button data-intro-pick="${i}" class="spell-pick ${state.picked===i?(i===cfg.answer?'right':'wrong'):''}" aria-pressed="${state.picked===i}">${mathMarkup(choice)}</button>`).join('')}</div>${wrong?'<p class="intro-wrong" role="status">Пока не совпало. Посмотри на правило и попробуй ещё.</p>':''}`:cfg.kind==='wake'?`<div class="wake-state"><span>«Искра проснулся»</span><strong>${state.env.X?'1 · Правда':'0 · Неправда'}</strong></div><button class="wake-button" data-intro-toggle="X" aria-label="${state.env.X?'Усыпить Искру':'Разбудить Искру'}">${state.env.X?'Усыпить Искру':'Разбудить Искру'} <span>${state.env.X?'1 → 0':'0 → 1'}</span></button>`:`<div class="value-switches" style="--count:${pairs.length}">${pairs.map(([key,value])=>`<button class="value-switch ${value?'is-true':'is-false'}" data-intro-toggle="${key}" aria-label="${key} = ${value}, ${value?'истина':'ложь'}. Нажми, чтобы поставить ${1-value}" aria-pressed="${!!value}"><span class="switch-name">${key}<small>значение</small></span><b>${value}</b><span class="switch-meaning">${value?'Истина':'Ложь'}</span><span class="switch-next">Нажми → ${1-value}</span></button>`).join('')}</div>`;
  const formula=cfg.kind==='wake'?'':cfg.kind==='compare'?`<div class="discovery-comparison">${formulaPanel(cfg.formula,{env:state.env,reveal:true})}${formulaPanel(cfg.other,{env:state.env,reveal:true})}</div>`:cfg.formula?formulaPanel(cfg.formula,{env:state.env,reveal:true}):'';
  return `<div class="lesson-container play-container">${header}<section class="discovery-play"><div class="mission-heading"><span class="mission-kicker">ЗНАКОМИМСЯ НА ПРИМЕРЕ</span><h1>${copy.title}</h1></div>${stage({active:complete,speech,sleeping:cfg.kind==='wake'&&!state.env.X})}<div class="discovery-controls"><p class="discovery-goal">${e(copy.goal)}</p><p class="tap-instruction" role="status">${e(introInstruction(lesson,state))}</p>${controls}${isScan?`<div class="scan-heading">Найдено ${state.seen.length} из ${2**pairs.length} наборов</div><div class="world-stamps" aria-label="Найденные наборы">${Array.from({length:2**pairs.length},(_,i)=>i.toString(2).padStart(pairs.length,'0')).map(row=>`<span class="${state.seen.includes(row)?'found':''}">${row}</span>`).join('')}</div>`:''}${formula}<p class="discovery-rule">${e(copy.rule)}</p><div class="discovery-footer"><button class="primary wide" data-action="next" ${!complete?'disabled':''}>${complete?'К задачам →':'К задачам'}</button><button class="quiet-link" data-action="skip-intro">Уже знаю это</button></div></div></section></div>`;
}

export function playHeader(title,total,index,icon){
  return `<div class="lesson-top play-top"><button class="icon-button" data-action="exit-lesson" aria-label="Выйти из урока с сохранением">${icon('close')}</button><div><span>${e(title)}</span><div class="lesson-progress-bars" aria-label="${Math.max(0,index)} из ${total} заданий">${Array.from({length:total},(_,i)=>`<i class="${i<index?'done':''}"></i>`).join('')}</div></div><span class="lesson-count">${Math.max(0,index)}<small> / ${total}</small></span></div>`;
}

function binaryContent(value){return `<b class="answer-digit">${value}</b><span class="answer-meaning">${value?'Истина':'Ложь'}</span>`;}
function choiceContent(value){try{return mathMarkup(value);}catch{return e(value);}}
function valuesMarkup(env){return `<div class="given-values"><span class="given-label">Дано</span><div>${Object.entries(env).map(([key,value])=>`<span class="given-value"><span>${key} =</span><b>${value}</b><small>${value?'истина':'ложь'}</small></span>`).join('')}</div></div>`;}
function feedbackMarkup(q,feedback,session,env){
  if(!feedback)return '';
  if(feedback.good)return `<div class="answer-flash" role="status">✓ Верно!${session.mode==='arena'?` <span>+${session.gained} ✦</span>`:''}</div>`;
  const calculations=q.formula&&env?renderCalculation(q.formula,env):'';
  return `<div class="compact-feedback bad" id="answer-feedback" role="status"><strong>Разберём вместе</strong>${calculations||`<p>${e(briefFeedback(q,false,feedback.text))}</p>`}<details class="why-details"><summary>Почему это работает?</summary><p>${e(feedback.text)}</p></details></div><button class="primary wide" data-action="retry">Попробовать ещё раз</button>`;
}

export function renderQuestion({q,lesson,session,selection,tableValues,formulaValue,feedback,hintOpen,theoryOpen,rowMistake,combo,header,icon}){
  const context=questionContext(q,lesson),activeRow=q.kind==='table'?tableRow(q,tableValues):-1,env=q.kind==='table'&&activeRow>=0?q.table.rows[activeRow].env:q.env;
  const binary=q.kind==='choice'&&q.options.length===2&&q.options.every(o=>/^[01]/.test(o));
  const talk=feedback?(feedback.good?'Получилось!': 'Сейчас разберёмся.'):rowMistake?'Давай по одному шагу.':q.kind==='table'?'Считаем одну строку за раз.':q.kind==='formula'?'Смысл должен остаться тем же.':q.formula?'Подставь числа вместо букв.':'Выбери свой ответ.';
  const title=q.kind==='table'?(activeRow===-1?'Таблица готова!':`Строка ${activeRow+1} из ${q.table.rows.length}`):q.kind==='formula'?'Запиши формулу с тем же смыслом':q.env?'Какой получится результат?':context.ask;
  const formula=context.formula?formulaPanel(context.formula,{comparison:q.comparison}):'';
  const answers=q.kind==='choice'?`<div class="answers ${binary?'binary-answers':'story-answers'}">${q.options.map((option,i)=>`<button class="answer ${selection===i?'selected':''} ${feedback&&selection===i?(feedback.good?'correct':'incorrect'):''}" data-answer="${i}" ${feedback?'disabled':''}>${binary?binaryContent(Number(option[0])):`<span class="answer-letter">${i+1}</span><span>${choiceContent(option)}</span>`}${feedback&&selection===i?icon(feedback.good?'check':'close',19):''}</button>`).join('')}</div>`:q.kind==='table'?renderWorlds(q,tableValues,activeRow,rowMistake,feedback):`<div class="spell-label"><label class="field-label" for="formula-answer">Твоя формула</label><button class="text-button" data-play="keyboard" aria-label="Ввести формулу с клавиатуры" ${feedback?'disabled':''}>⌨</button></div><div class="spell-input-wrap"><input id="formula-answer" class="formula-input" inputmode="none" maxlength="200" value="${e(formulaValue)}" placeholder="Нажимай на знаки внизу" autocomplete="off" autocapitalize="characters" spellcheck="false" ${feedback?'disabled':''}><button class="rune-erase" data-play="erase" aria-label="Удалить последний символ" ${feedback?'disabled':''}>⌫</button></div><div class="rune-tray" aria-label="Знаки для формулы">${spellTiles(q).map(s=>`<button type="button" data-insert="${s}" data-target="formula-answer" aria-label="Вставить ${s==='¬'?'НЕ':s}" ${feedback?'disabled':''}>${s}</button>`).join('')}</div>${!feedback?`<button class="primary wide cast-button" data-action="check" ${!formulaValue.trim()?'disabled':''}>Проверить формулу</button>`:''}`;
  return `<div class="lesson-container play-container">${header}<section class="question-area play-question ${feedback?.good?'question-win':''}"><div class="quest-mini-head"><span>${q.kind==='table'?'ТАБЛИЦА ИСТИННОСТИ':q.kind==='formula'?'ПРЕОБРАЗОВАНИЕ':'ТВОЯ ЗАДАЧА'}</span><button class="text-button" data-action="theory">${icon('book',17)} Правило</button></div>${session.mode==='arena'?'':stage({small:true,speech:talk,reaction:feedback?.good?'cheer':''})}<div class="question-interaction"><h1>${e(title)}</h1>${context.story?`<div class="story-key">${Object.entries(context.story).map(([key,text])=>`<span><b>${key}</b> ${e(text)}</span>`).join('')}</div>`:''}${context.clue?`<p class="tiny-discovery">${e(context.clue)}</p>`:''}${env?valuesMarkup(env):''}${formula}${q.formula?operatorGuide(q.formula):''}${theoryOpen?`<div class="one-rule"><p>${e(discoveryFor(lesson).rule)}</p></div><details class="why-details"><summary>Подробнее и пример</summary><p>${e(lesson.theory)}</p><p>${e(lesson.example)}</p></details>`:''}${answers}${hintOpen?`<div class="hint-box">${e(q.hint)}</div>`:''}${feedbackMarkup(q,feedback,session,env)}<div class="play-helper-row"><button class="text-button" data-action="hint">${icon('help',17)} ${hintOpen?'Спрятать подсказку':'Нужна подсказка'}</button></div></div></section></div>`;
}

function renderWorlds(q,values,index,mistake,feedback){
  return `<div class="world-progress" aria-label="Решённые строки таблицы">${q.table.rows.map((row,i)=>`<span class="world-dot ${values[i]!==undefined?'solved':i===index?'current':''}" aria-label="Строка ${i+1}, ${Object.entries(row.env).map(([key,value])=>`${key} = ${value}`).join(', ')}${values[i]!==undefined?', результат '+values[i]:', ещё не решена'}"><span>${Object.values(row.env).join(' ')}</span><b>${values[i]!==undefined?values[i]:'?'}</b></span>`).join('')}</div>${!feedback?`<div class="answers binary-answers">${[0,1].map(value=>`<button class="answer" data-table-value="${value}" ${mistake?'disabled':''}>${binaryContent(value)}</button>`).join('')}</div>`:''}${mistake?`<div class="row-mistake" role="status"><strong>Разберём эту строку</strong>${renderCalculation(q.formula,q.table.rows[index].env)}<details class="why-details"><summary>Почему это работает?</summary><p>${e(q.why)}</p></details><button class="primary wide" data-play="retry-row">Попробовать ещё раз</button></div>`:''}`;
}

export function renderLoot({result,lesson,nextLesson,opened,icon}){const loot=lesson?discoveryFor(lesson):{name:'Искра памяти',symbol:'✦',rule:'Повторение укрепляет твои открытия.'};return `<section class="loot-screen ${opened?'opened':''}"><span class="mission-kicker">${result.practice?'ИСКРА ПАМЯТИ':'СЕКРЕТ НАЙДЕН'}</span><h1>${opened?loot.name:'Что там в сундуке?'}</h1><div class="loot-stage">${sparks(8)}<button class="loot-chest" data-play="open-loot" aria-label="${opened?'Сундук открыт':'Открыть сундук с наградой'}" ${opened?'disabled':''}><img src="./assets/chest.png" width="1024" height="1024" alt="Волшебный сундук">${!opened?'<span>Нажми!</span>':''}</button><div class="loot-rune" ${!opened?'aria-hidden="true"':''}><span>${loot.symbol}</span></div><img class="loot-dragon" src="./assets/iskra.png" alt="Искра радуется" width="1254" height="1254"></div>${opened?`<p class="loot-rule">${loot.rule}</p><span class="loot-keepsake">${result.practice?'Твои открытия стали крепче':'Сохранено в твоей коллекции'}</span>`:'<p class="loot-rule">За каждой задачей прячется маленькое открытие.</p>'}<div class="loot-stats"><span>✦ +${result.xp} XP</span><span class="loot-stars" aria-label="${result.stars} из 3 звёзд">${'★'.repeat(result.stars)}${'☆'.repeat(3-result.stars)}</span></div>${opened&&!result.practice&&nextLesson?`<button class="primary wide" data-action="start" data-id="${nextLesson.id}">В следующее приключение ${icon('chevron',19)}</button>`:''}<button class="${opened?'secondary':'quiet-link'} wide" data-nav="map">На карту</button></section>`;}
export function collection(lessons,progress){return `<section class="rune-collection"><div class="section-title"><h2>Мои находки</h2><span>${Object.keys(progress.completed).length} / 24</span></div><div class="collection-grid">${lessons.map(l=>{const d=discoveryFor(l),owned=!!progress.completed[l.id];return `<button class="collectible ${owned?'owned':''}" data-collectible="${l.id}" aria-label="${owned?d.name:'Ещё не найдено. Урок '+l.title}"><span>${owned?d.symbol:'?'}</span><small>${owned?d.name:'Секрет'}</small></button>`;}).join('')}</div></section>`;}
