import {HOME_TIERS,DECORATIONS,bondLevel} from './pets.js';
import {STORIES,storyUnlocked,currentEncounter} from './expeditions.js';
import {formulaPanel,mathMarkup,renderCalculation} from './math-view.js';
import {parse,evaluate} from './logic.js';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const portions=n=>n+' '+(n%100>=11&&n%100<=14?'порций':n%10===1?'порция':n%10>=2&&n%10<=4?'порции':'порций');
const poseNames={idle:'ждёт тебя',eat:'ест',happy:'радуется',play:'играет с мячиком',sleep:'спит',curious:'прислушивается'};
function homeScene(s,pose='idle',light=true,game=null){return `<div class="habitat tier-${s.home.tier} ${light?'light-on':''}"><button class="pet-atlas pose-${pose}" data-pet="touch" aria-label="${e(s.pet.name)} ${poseNames[pose]}. Погладить"></button><div class="home-leaves" aria-hidden="true"></div>${s.stories.lights?'<div class="ambient-fireflies" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>':''}${s.home.tier>=2?'<div class="home-flowers" aria-hidden="true">❀ ✿ ❀</div>':''}${s.home.tier>=3?'<div class="home-railing" aria-hidden="true"></div>':''}${s.home.tier>=4?'<div class="home-garland" aria-hidden="true">✧ · ✧ · ✧ · ✧ · ✧</div>':''}${s.home.equipped.includes('lantern')?'<button class="home-prop jar" data-pet="lantern" aria-label="Включить или погасить светлячков"><i></i><i></i><i></i></button>':''}${s.home.equipped.includes('cushion')?'<button class="home-prop cushion" data-pet="sleep" aria-label="Уложить Искру на подушку">☁</button>':''}${s.home.equipped.includes('chimes')?'<button class="home-prop chimes" data-pet="chimes" aria-label="Поиграть с музыкой ветра">♫</button>':''}${game?`<div class="pet-ball-game"><span class="pet-ball-score">ПОЙМАЙ МЯЧ · ${game.hits} / 3</span><button class="pet-ball-target ball-spot-${game.hits}" data-pet="catch-ball" aria-label="Поймать мяч, бросок ${game.hits+1} из 3"><i></i></button><button class="pet-ball-exit" data-pet="stop-ball" aria-label="Закончить игру с мячом">×</button></div>`:''}<span class="home-scene-label">${e(HOME_TIERS[s.home.tier].name)}</span></div>`;}
export function petHome(s,{pose='idle',message='',panel=null,light=true,game=null}={}){
  const b=bondLevel(s.pet.bond),next=STORIES.find(q=>!s.stories[q.id])||STORIES[0],active=s.active;
  const speech=message||(s.pet.appetite?'Привет! Перекусим и отправимся в путь?':'Я сыт и готов к приключениям!');
  return `<div class="pet-home"><header class="pet-home-heading"><div><span class="pet-kicker">НАШ МАЛЕНЬКИЙ МИР</span><h1>${e(s.pet.name)}<button class="pet-rename" data-pet="rename" aria-label="Изменить имя питомца">✎</button></h1></div><span class="shell-wallet" aria-label="${s.shells} ракушек">◉ <b>${s.shells}</b><small>ракушек</small></span></header><div class="bond-strip"><span>♡ ${b.name}</span><span>${s.pet.bond}${b.ceiling?' / '+b.ceiling:''}</span></div><div class="bond-track" role="progressbar" aria-label="Дружба с питомцем" aria-valuenow="${Math.min(s.pet.bond,b.ceiling||s.pet.bond)}" aria-valuemin="0" aria-valuemax="${b.ceiling||Math.max(1,s.pet.bond)}"><i style="width:${Math.min(100,s.pet.bond/(b.ceiling||1)*100)}%"></i></div>${homeScene(s,pose,light,game)}<div class="pet-speech" role="status">${e(speech)}</div><div class="pet-actions"><button data-pet="feed-panel" aria-expanded="${panel==='food'}"><span>◒</span>Покормить<small>${portions(s.rations+s.favoriteMeals)}</small></button><button data-pet="play"><span>◉</span>Поиграть<small>${s.pet.care.play?'Лови мяч!':'+2 дружбы'}</small></button><button data-pet="decor-panel" aria-expanded="${panel==='decor'}"><span>⌂</span>Украсить<small>${s.home.owned.length} ${s.home.owned.length===1?'предмет':s.home.owned.length>=2&&s.home.owned.length<=4?'предмета':'предметов'}</small></button></div>${panel==='food'?foodPanel(s):panel==='decor'?decorPanel(s):panel==='album'?albumPanel(s):''}<button class="pet-adventure-cta" data-expedition="${active?.storyId||next.id}"><span class="adventure-cta-icon">${active?'↗':next.icon}</span><span><small>${active?'ПРОДОЛЖИМ С ТОГО ЖЕ МЕСТА':'В ПРИКЛЮЧЕНИЕ · 3–5 МИН'}</small><strong>${active?STORIES.find(q=>q.id===active.storyId).title:next.title}</strong></span><b>→</b></button><div class="pet-home-links"><button data-pet="stories">Все приключения</button><button data-pet="album-panel">Наши воспоминания</button></div>${panel==='stories'?storyPanel(s):''}<button class="pet-study-link" data-nav="map">Продолжить учиться · +20 ◉ и еда →</button>${s.pet.bond>=12?'<button class="pet-secret-gesture" data-pet="high-five">✧ Наш секретный жест · дай пять</button>':''}<div class="pet-next-discovery"><span>✧</span><div><strong>${b.next}</strong><small>${b.ceiling?'Ещё '+Math.max(0,b.ceiling-s.pet.bond)+' дружбы до следующего открытия.':'Продолжим собирать истории вместе.'}</small></div></div></div>`;
}
function panelHead(title){return `<div class="pet-panel-head"><h2>${title}</h2><button data-pet="close-panel" aria-label="Закрыть раздел">×</button></div>`;}
function foodPanel(s){return `<section class="pet-panel" id="pet-panel">${panelHead('Что у нас вкусного?')}<p class="pet-panel-note">${s.pet.appetite?'Можно перекусить.':'Питомец сыт. Приготовленное сохраним на потом.'}</p><div class="food-choices"><button data-pet="feed" ${!s.pet.appetite||!s.rations?'disabled':''}><span>◒</span><strong>Лесная порция</strong><small>В запасе: ${s.rations}</small></button><button data-pet="feed-favorite" ${!s.pet.appetite||!s.favoriteMeals?'disabled':''}><span>❀</span><strong>Ягодная лепёшка</strong><small>Любимая · ${s.favoriteMeals} шт.</small></button></div>${s.stories.picnic?`<button class="pet-small-primary" data-pet="cook" ${s.shells<6?'disabled':''}>Приготовить лепёшку · 6 ◉</button>`:'<p class="pet-panel-note">Рецепт лепёшки ждёт в «Ягодном пикнике».</p>'}<p class="pet-panel-note">Порции приносят приключения, уроки и гонки.</p></section>`;}
function decorPanel(s){const next=HOME_TIERS[s.home.tier+1];return `<section class="pet-panel" id="pet-panel">${panelHead('Сделаем дом своим')}<div class="decor-list">${DECORATIONS.map(d=>{const owned=s.home.owned.includes(d.id),equipped=s.home.equipped.includes(d.id);return `<div class="decor-item"><span class="decor-preview decor-${d.id}">${d.icon}</span><div><strong>${d.name}</strong><p>${d.description}</p><button data-pet="${owned?'equip':'buy'}" data-item="${d.id}" ${!owned&&s.shells<d.price?'disabled':''}>${owned?equipped?'Убрать в коллекцию':'Поставить дома':`Купить · ${d.price} ◉`}</button></div></div>`;}).join('')}</div>${next?`<div class="home-upgrade"><small>СЛЕДУЮЩАЯ СТУПЕНЬ</small><h3>${next.name}</h3><p>${['','Листья укроют вход в гнездо.','У порога расцветёт маленький сад.','Появится деревянная веранда.','Весь дом украсит гирлянда.'][s.home.tier+1]}</p><span>${next.cost} ◉ · ${next.bond} дружбы</span><button class="pet-small-primary" data-pet="upgrade" ${s.shells<next.cost||s.pet.bond<next.bond?'disabled':''}>Улучшить дом</button></div>`:'<p>Дом мечты готов. Все твои вещи остаются здесь.</p>'}</section>`;}
function storyPanel(s){return `<section class="pet-panel" id="pet-panel">${panelHead('Куда пойдём?')}<div class="story-list">${STORIES.map(q=>`<button data-expedition="${q.id}" ${!storyUnlocked(s,q.id)?'disabled':''}><span>${q.icon}</span><div><strong>${q.title}</strong><small>${!storyUnlocked(s,q.id)?'Сначала: '+STORIES.find(x=>x.id===q.after).title:q.subtitle}</small><small>${storyUnlocked(s,q.id)?s.stories[q.id]?'Новый поход · +20 ◉':'Первая история · +30 ◉':''}</small></div><b>${s.stories[q.id]?'↻':storyUnlocked(s,q.id)?'→':'⌑'}</b></button>`).join('')}</div></section>`;}
function albumPanel(s){return `<section class="pet-panel" id="pet-panel">${panelHead('Наши воспоминания')}<div class="memory-list">${STORIES.map(q=>`<div class="${s.stories[q.id]?'remembered':''}"><span>${s.stories[q.id]?q.icon:'?'}</span><div><strong>${s.stories[q.id]?q.reward:q.title}</strong><small>${s.stories[q.id]?'Мы сделали это вместе':'Воспоминание ещё впереди'}</small></div></div>`).join('')}</div></section>`;}
function encounterScene(q,a){
  const open=q.kind==='switch'?evaluate(parse(q.formula),a.env)===q.target:a.passed;
  return `<div class="encounter-scene world-${q.scene} ${q.night?'night-journey':''} ${open?'mechanism-open':''} ${a.passed?'encounter-passed':''}" aria-label="${open?'Путь открыт':'Препятствие на пути'}"><div class="encounter-sky"></div>${q.night?'<div class="ambient-fireflies" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>':''}${q.scene==='recipe'?`<div class="recipe-basket" aria-label="Корзинка: ${a.env.X?'ягоды, ':''}${a.env.Y?'мёд, ':''}${a.env.Z?'испорченный плод':'без испорченных плодов'}"><div class="basket-food">${a.env.X?'<span class="basket-berries">●<i>●</i><b>●</b></span>':''}${a.env.Y?'<span class="basket-honey">мёд</span>':''}${a.env.Z?'<span class="basket-spoiled">×</span>':''}</div><span class="basket-weave"></span></div>`:''}<div class="scene-river"></div><div class="scene-path"></div><div class="scene-gate"><i></i><i></i><span>${q.scene==='home'?'⌂':q.scene==='rune'?'?':q.scene==='lamp'?'☼':'✧'}</span></div><img class="encounter-dragon" src="./assets/iskra.png" width="1254" height="1254" alt="Искра у препятствия" draggable="false"><span class="mechanism-label">${a.passed?q.success:q.scene==='recipe'?open?'Можно готовить!':'Собери полезные продукты':open?'Можно пройти':q.scene==='lamp'?'Починим вместе':q.scene==='rune'?'Здесь не хватает руны':'Путь пока закрыт'}</span></div>`;
}
const given=env=>`<div class="quest-given">${Object.entries(env).map(([k,v])=>`<span>${k} = <b>${v}</b><small>${v?'истина':'ложь'}</small></span>`).join('')}</div>`;
export function expeditionView(s,{hint=false}={}){
  const a=s.active,q=currentEncounter(s),story=STORIES.find(x=>x.id===a?.storyId);
  if(!a||!q)return expeditionResult(s);
  const blocked=a.passed||a.feedback==='wrong';
  let controls='';
  if(q.kind==='switch')controls=`<div class="quest-switches ${Object.keys(a.env).length===3?'three-switches':''}">${Object.entries(a.env).map(([k,v])=>`<button data-quest-toggle="${k}" aria-label="${k} = ${v}. Поменять на ${1-v}" aria-pressed="${!!v}" class="${v?'on':''}" ${blocked?'disabled':''}><span>${q.labels?e(q.labels[k])+' · ':''}${k}</span><b>${v}</b><small>${q.labels?v?'Есть · 1':'Нет · 0':v?'Истина':'Ложь'}</small><em>Нажми → ${1-v}</em></button>`).join('')}</div>${formulaPanel(q.formula,{env:a.env,reveal:true})}<button class="quest-primary" data-quest="check" ${blocked?'disabled':''}>${q.scene==='recipe'?'Приготовить':q.scene==='home'?'Открыть дом':'Попробовать пройти'} →</button>`;
  if(q.kind==='repair')controls=`${given(q.env)}<div class="repair-steps">${q.lines.map((line,i)=>`<button data-quest-answer="${i}" ${blocked?'disabled':''} class="${a.choice===i?(a.passed?'chosen-good':'chosen-wrong'):''}"><span>${i+1}</span><b>${e(line)}</b><small>${i===0?'Берём значение':q.stepLabel||'Применяем НЕ'}</small></button>`).join('')}</div>`;
  if(q.kind==='rune')controls=`<div class="rune-cases">${q.cases.map(c=>`<div><span>${c.X}</span><b class="rune-hole">?</b><span>${c.Y}</span><span>= <strong>${c.result}</strong></span></div>`).join('')}</div><div class="quest-rune-choices">${q.options.map((v,i)=>`<button data-quest-answer="${i}" ${blocked?'disabled':''} class="${a.choice===i?(a.passed?'chosen-good':'chosen-wrong'):''}"><b>${v}</b><span>${v==='∧'?'И':'ИЛИ'}</span></button>`).join('')}</div>`;
  if(q.kind==='route')controls=`${given(q.env)}<div class="quest-routes">${q.options.map((v,i)=>`<button data-quest-answer="${i}" ${blocked?'disabled':''} class="${a.choice===i?(a.passed?'chosen-good':'chosen-wrong'):''}"><span>ТРОПА ${i===0?'А':'Б'}</span><b>${mathMarkup(v)}</b><small>Пойти сюда →</small></button>`).join('')}</div>`;
  const why=q.kind==='switch'?renderCalculation(q.formula,a.env)+'<p>'+e(q.hint)+'</p>':q.kind==='repair'?q.repair:q.hint;
  return `<div class="expedition-container"><header class="quest-top"><button data-quest="exit" aria-label="Домой с сохранением">×</button><div><span>${story.title}</span><div class="quest-progress">${[0,1,2,3,4].map(i=>`<i class="${i<a.step?'done':i===a.step?'current':''}"></i>`).join('')}</div></div><span>${a.step+1}<small> / 5</small></span></header><section class="encounter"><div class="encounter-heading"><span class="pet-kicker">${{switch:'УПРАВЛЯЙ',repair:'НАЙДИ ОШИБКУ',rune:'СОБЕРИ ПРАВИЛО',route:'ВЫБЕРИ ПУТЬ'}[q.kind]}</span><h1>${q.title}</h1><p>${q.goal}</p></div>${encounterScene(q,a)}<div class="encounter-controls"><p class="quest-rule">${q.rule}</p>${controls}${a.feedback==='wrong'?`<div class="quest-feedback" role="status"><strong>Разберём вместе</strong><div>${q.kind==='switch'?why:e(why)}</div><button data-quest="retry">Попробовать ещё раз</button></div>`:a.passed?`<div class="quest-success" role="status">✓ ${q.kind==='repair'?e(q.repair):q.success}</div>`:`<button class="quest-hint" data-quest="hint" aria-expanded="${hint}">? ${hint?'Спрятать подсказку':'Нужна подсказка'}</button>${hint?`<p class="quest-hint-copy">${q.hint}</p>`:''}`}</div></section></div>`;
}
export function expeditionResult(s){const r=s.lastResult,story=STORIES.find(x=>x.id===r?.storyId);if(!r||!story)return '<button class="primary" data-quest="exit">Домой</button>';return `<div class="expedition-result"><span class="pet-kicker">МЫ СДЕЛАЛИ ЭТО ВМЕСТЕ</span><h1>${story.reward}</h1><div class="pet-atlas pose-happy result-pet" role="img" aria-label="Искра радуется"></div><div class="expedition-rewards"><span>+${r.shells} ◉<small>ракушек</small></span><span>+1 ◒<small>порция</small></span><span>+8 ♡<small>дружбы</small></span></div><p>${r.storyId==='picnic'?'Теперь можно приготовить любимую лепёшку!':'Дома нас ждут вкусная порция и новые вещи.'}</p><button class="quest-primary" data-quest="exit">Домой →</button><button class="quest-hint" data-nav="map">Открыть учебную карту</button></div>`;}
